-- +goose Up
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT UNIQUE,
    name          TEXT NOT NULL,
    password_hash TEXT,
    is_guest      BOOLEAN NOT NULL DEFAULT FALSE,
    invited_by    BIGINT REFERENCES users(id),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
    token_hash TEXT PRIMARY KEY,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

CREATE TABLE groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    kind            TEXT NOT NULL DEFAULT 'group' CHECK (kind IN ('group', 'direct')),
    created_by      BIGINT NOT NULL REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invites (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       TEXT NOT NULL,
    group_id    BIGINT REFERENCES groups(id) ON DELETE SET NULL,
    token_hash  TEXT NOT NULL UNIQUE,
    created_by  BIGINT NOT NULL REFERENCES users(id),
    expires_at  TIMESTAMPTZ NOT NULL,
    accepted_by BIGINT REFERENCES users(id),
    accepted_at TIMESTAMPTZ
);

CREATE TABLE memberships (
    group_id BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, user_id)
);

CREATE TABLE expenses (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id     BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    description  TEXT NOT NULL,
    notes        TEXT NOT NULL DEFAULT '',
    category     TEXT NOT NULL DEFAULT 'general',
    date         DATE NOT NULL,
    is_payment   BOOLEAN NOT NULL DEFAULT FALSE,
    split_mode   TEXT NOT NULL DEFAULT 'even',
    receipt_file TEXT,
    created_by   BIGINT NOT NULL REFERENCES users(id),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMPTZ
);
CREATE INDEX idx_expenses_group ON expenses(group_id, date);

CREATE TABLE expense_shares (
    expense_id BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    paid       BIGINT NOT NULL DEFAULT 0,
    owed       BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (expense_id, user_id)
);
CREATE INDEX idx_expense_shares_user ON expense_shares(user_id);

CREATE TABLE expense_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_id  BIGINT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
    position    INTEGER NOT NULL,
    description TEXT NOT NULL,
    amount      BIGINT NOT NULL
);
CREATE INDEX idx_expense_items_expense ON expense_items(expense_id, position);

CREATE TABLE item_shares (
    item_id BIGINT NOT NULL REFERENCES expense_items(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, user_id)
);

CREATE TABLE activity (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id   BIGINT REFERENCES groups(id) ON DELETE CASCADE,
    expense_id BIGINT REFERENCES expenses(id) ON DELETE SET NULL,
    actor_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    type       TEXT NOT NULL,
    detail     TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_activity_group ON activity(group_id, id DESC);

CREATE TABLE receipts (
    name         TEXT PRIMARY KEY,
    content_type TEXT NOT NULL,
    data         BYTEA NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
